"""
SpecStory → Export Transcript 格式清洗脚本

用途：将 Cursor SpecStory history 文件清洗为和 Export Transcript 一致的 MD 格式
依赖：仅标准库（re, pathlib, sys）

调用方式1（命令行）：
    python specstory_clean.py input.md output.md

调用方式2（函数导入，供 N8N Code 节点使用）：
    from specstory_clean import clean_specstory
    result = clean_specstory(text_str)  # 输入字符串，返回字符串

格式依据（每条规则均标注来源）：
    基准文件：数字分身/待确认/用这个cursor_4_6max_备份_20260317.md（第87行起）
    SpecStory源：.specstory/history/2026-03-17_04-00Z-总顾问(大脑常驻层)4-6max.md
"""

import re
import sys
from datetime import datetime
from pathlib import Path


# ============================================================
# 格式常量（全部来自实际文件，不猜）
# ============================================================

# 依据：SpecStory源 第1行
RE_GENERATED_COMMENT = re.compile(r'^<!-- Generated by SpecStory.*-->[ \t]*$', re.MULTILINE)

# 依据：SpecStory源 第3行
RE_SESSION_COMMENT = re.compile(r'^<!-- cursor Session.*-->[ \t]*$', re.MULTILINE)

# 依据：SpecStory源 第5行
# 格式：# 标题 (2026-03-17 04:00Z)
RE_TITLE_LINE = re.compile(r'^(# .+?) \(\d{4}-\d{2}-\d{2} \d{2}:\d{2}Z\)[ \t]*$', re.MULTILINE)

# 依据：SpecStory源 第7行 / SpecStory源中也有带时间戳的格式 _**User (时间戳)**_
RE_USER_ROLE = re.compile(r'^_\*\*User(?: \([^)]*\))?\*\*_[ \t]*$', re.MULTILINE)

# 依据：SpecStory源 第13行（不同消息中 model 和 mode 有变化，用正则匹配所有变体）
RE_AGENT_ROLE = re.compile(r'^_\*\*Agent \(model [^,]+, mode [^)]+\)\*\*_[ \t]*$', re.MULTILINE)

# 依据：SpecStory源 第19行（tool-use开始）、第26行（tool-use结束）
# 完整块：<tool-use ...> ... </tool-use>（跨行，贪婪最短匹配）
RE_TOOL_USE_BLOCK = re.compile(
    r'<tool-use\b[^>]*>.*?</tool-use>',
    re.DOTALL
)

# 依据：.specstory/history/2026-03-13_16-29Z-回家测试系统.md 第15行（thinking块实际格式）
# 格式：<think><details><summary>Thought Process</summary>...内容...</details></think>
# 约束：<think> 必须在行首（^），避免误匹配行内代码里的 `<think>` 文字
# 结束标记 </details></think> 也必须在行尾
RE_THINKING_BLOCK = re.compile(
    r'^<think>.*?</details></think>[ \t]*$',
    re.MULTILINE | re.DOTALL
)

# 依据：SpecStory源 第185/189行（"This operation was aborted"，Export Transcript基准中无对应）
RE_ABORTED = re.compile(r'^This operation was aborted[ \t]*$', re.MULTILINE)

# 依据：SpecStory源各处出现的分隔线
RE_SEPARATOR = re.compile(r'^---[ \t]*$', re.MULTILINE)

# 依据：指令文件第85-87行（系统XML标签，早期文件有）
# <user_query> 只删标签不删内容；其余标签连同内容一起删除
SYSTEM_TAG_NAMES_DELETE_CONTENT = [
    'open_and_recently_viewed_files',
    'system_reminder',
    'attached_files',
    'agent_transcripts',
    'git_status',
    'rules',
    'agent_skills',
    'user_info',
]
RE_SYSTEM_TAGS_WITH_CONTENT = re.compile(
    r'<(' + '|'.join(SYSTEM_TAG_NAMES_DELETE_CONTENT) + r')[^>]*>.*?</\1>',
    re.DOTALL
)
# <user_query> 只删开闭标签，保留内容
RE_USER_QUERY_OPEN = re.compile(r'<user_query[^>]*>', re.MULTILINE)
RE_USER_QUERY_CLOSE = re.compile(r'</user_query>', re.MULTILINE)


# ============================================================
# 核心清洗函数
# ============================================================

def clean_specstory(text: str) -> str:
    """
    输入：SpecStory MD 文件的完整文本（字符串）
    输出：清洗后的 MD 文本（字符串），格式与 Export Transcript 一致

    处理顺序与指令中9类过滤项对应：
    #5 头部HTML注释 → #6 标题行 → #2 thinking块 → #1 tool-use块（含合并） →
    #7 系统XML标签 → #3 Agent角色行 → #4 User角色行 →
    #8/#9 连续分隔线合并
    """

    # ----------------------------------------
    # #5 删除SpecStory头部HTML注释
    # 依据：SpecStory源 第1行 `<!-- Generated by SpecStory, Markdown v2.1.0 -->`
    # 依据：SpecStory源 第3行 `<!-- cursor Session UUID (时间) -->`
    # ----------------------------------------
    text = RE_GENERATED_COMMENT.sub('', text)
    text = RE_SESSION_COMMENT.sub('', text)

    # ----------------------------------------
    # #6 标题行改写
    # 依据：SpecStory源 第5行 `# 总顾问（大脑常驻层）4.6MAX (2026-03-17 04:00Z)`
    # 依据：基准第87-88行 `# 总顾问（大脑常驻层）4.6MAX` + `_Exported on ...from Cursor (版本)_`
    # 改写为：`# 标题` + 换行 + `_Cleaned from SpecStory on 日期_`
    # ----------------------------------------
    today_str = datetime.now().strftime('%Y-%m-%d')
    def replace_title(m):
        title = m.group(1)
        return f'{title}\n_Cleaned from SpecStory on {today_str}_'
    text = RE_TITLE_LINE.sub(replace_title, text)

    # ----------------------------------------
    # #2 删除thinking块
    # 依据：.specstory/history/2026-03-13_16-29Z-回家测试系统.md 第15行
    # 格式：<think><details><summary>Thought Process</summary>...内容...</details></think>
    # 整块删除（含前后由分隔线清理步骤处理的空行）
    # ----------------------------------------
    text = RE_THINKING_BLOCK.sub('', text)

    # ----------------------------------------
    # "This operation was aborted" 行删除
    # 依据：SpecStory源 第185/189行；基准文件对应位置无此行
    # ----------------------------------------
    text = RE_ABORTED.sub('', text)

    # ----------------------------------------
    # #7 系统XML标签处理（早期文件）
    # 依据：指令文件第85-87行
    # 其余系统标签连内容一起删除；<user_query>只删标签保留内容
    # ----------------------------------------
    text = RE_SYSTEM_TAGS_WITH_CONTENT.sub('', text)
    text = RE_USER_QUERY_OPEN.sub('', text)
    text = RE_USER_QUERY_CLOSE.sub('', text)

    # ----------------------------------------
    # #1 tool-use块删除 + AI回复合并
    # 依据：SpecStory源 第19行（tool-use开始）、第26行（tool-use结束）
    # 依据：基准第98-142行（同一**Cursor**块下多段文字直接用空行分隔）
    #
    # 核心逻辑：
    # 1. 将整个文档按"角色块"切分（User / Agent / tool-use / 其他）
    # 2. 删除所有 tool-use 块
    # 3. 同一 Agent 发言中被 tool-use 分隔的文字段合并为一个 **Cursor** 块
    # ----------------------------------------
    text = _merge_agent_blocks(text)

    # ----------------------------------------
    # #3 Agent角色行改写
    # 依据：SpecStory源 第13行 `_**Agent (model claude-4.6-opus-max, mode Agent)**_`
    # 改写为：`**Cursor (model ..., mode ...)**`，保留模型型号，去掉斜体前缀
    # ----------------------------------------
    def replace_agent_role(m):
        # 提取括号内的模型信息，保留到新格式中
        inner = re.search(r'\(model [^)]+\)', m.group(0))
        if inner:
            return f'**Cursor {inner.group(0)}**'
        return '**Cursor**'
    text = RE_AGENT_ROLE.sub(replace_agent_role, text)

    # ----------------------------------------
    # #4 User角色行改写
    # 依据：SpecStory源 第7行 `_**User**_`（也有带时间戳的变体）
    # 依据：基准第92行 `**User**`
    # ----------------------------------------
    text = RE_USER_ROLE.sub('**User**', text)

    # ----------------------------------------
    # #8/#9 连续分隔线 + 空行合并
    # 依据：指令文件第89-96行
    # 删除 tool-use/thinking 后会留下连续 `---` 和空行，合并为单个 `---` + 一个空行
    # ----------------------------------------
    text = _collapse_separators(text)

    # 清理开头/结尾多余空行
    text = text.strip() + '\n'

    return text


def _merge_agent_blocks(text: str) -> str:
    """
    删除所有 tool-use 块，并将同一 Agent 发言中被 tool-use 分隔的文字段合并。

    处理思路：
    - 按行遍历，识别"当前在哪个块里"
    - 遇到 tool-use 开始标记 → 进入 tool-use 状态，跳过直到 </tool-use>
    - 遇到 Agent 角色行 → 开始收集当前 Agent 发言的文字段
    - 遇到 User 角色行 → 输出已收集的 Agent 发言，切换到 User 状态
    - Agent 发言的多个文字段之间只用空行分隔（不重复角色行）

    依据：
    - tool-use 开始：SpecStory源 第19行
    - tool-use 结束：SpecStory源 第26行
    - 合并后格式：基准第98-142行（一个**Cursor**块下多段文字）
    """
    lines = text.split('\n')
    output_lines = []

    in_tool_use = False          # 当前是否在 tool-use 块内
    tool_use_depth = 0           # 嵌套深度（以防万一）

    in_agent_block = False       # 当前是否在 Agent 发言块内
    agent_role_line = ''         # 当前 Agent 块的角色行原文
    agent_content_lines = []     # 当前 Agent 块收集的内容行（不含角色行和分隔线）

    def flush_agent():
        """把当前 Agent 块的内容行输出到 output_lines，空内容则跳过"""
        # 去掉内容块首尾的纯空行
        content = '\n'.join(agent_content_lines).strip()
        # 过滤掉只有---和空行的空块（无实质文字内容）
        content_no_sep = re.sub(r'^---\s*$', '', content, flags=re.MULTILINE).strip()
        if content_no_sep:
            output_lines.append(agent_role_line)
            output_lines.append('')
            output_lines.append(content)
            output_lines.append('')
            output_lines.append('---')
            output_lines.append('')

    def flush_user(user_role_line_val, user_content_lines_val):
        """把User块内容输出到output_lines，空内容则跳过"""
        content = '\n'.join(user_content_lines_val).strip()
        if content:
            output_lines.append(user_role_line_val)
            output_lines.append('')
            output_lines.append(content)
            output_lines.append('')
            output_lines.append('---')
            output_lines.append('')

    RE_TOOL_USE_OPEN = re.compile(r'^<tool-use\b')
    RE_TOOL_USE_CLOSE = re.compile(r'</tool-use>\s*$')
    RE_AGENT_LINE = re.compile(r'^_\*\*Agent \(model [^,]+, mode [^)]+\)\*\*_\s*$')
    RE_USER_LINE = re.compile(r'^_\*\*User(?: \([^)]*\))?\*\*_\s*$')
    RE_SEP_LINE = re.compile(r'^---\s*$')

    # User块缓冲（用于过滤空User块）
    in_user_block = False
    user_role_line = ''
    user_content_lines = []

    # Agent块内：角色行之后的第一个---是SpecStory固定结构，必须丢弃
    # 后续的---（包括tool-use结束后的、以及AI正文章节分隔）需区分处理
    agent_header_sep_consumed = False  # 是否已消耗掉角色行后的第一个---
    just_ended_tool_use = False        # 刚结束一个tool-use块

    i = 0
    while i < len(lines):
        line = lines[i]

        # --- 处理 tool-use 块 ---
        if RE_TOOL_USE_OPEN.match(line):
            in_tool_use = True
            tool_use_depth = 1
            just_ended_tool_use = False
            i += 1
            continue

        if in_tool_use:
            if RE_TOOL_USE_CLOSE.search(line):
                tool_use_depth -= 1
                if tool_use_depth <= 0:
                    in_tool_use = False
                    just_ended_tool_use = True  # 标记刚结束tool-use
            # tool-use 内容全部丢弃
            i += 1
            continue

        # --- 处理 Agent 角色行 ---
        if RE_AGENT_LINE.match(line):
            if in_user_block:
                flush_user(user_role_line, user_content_lines)
                in_user_block = False
                user_content_lines = []
            if not in_agent_block:
                in_agent_block = True
                agent_role_line = line.rstrip()
                agent_content_lines = []
                agent_header_sep_consumed = False  # 重置：新Agent块，首个---还未消耗
            just_ended_tool_use = False
            i += 1
            continue

        # --- 处理 User 角色行 ---
        if RE_USER_LINE.match(line):
            if in_agent_block:
                flush_agent()
                in_agent_block = False
                agent_content_lines = []
            elif in_user_block:
                flush_user(user_role_line, user_content_lines)
                in_user_block = False
                user_content_lines = []
            in_user_block = True
            user_role_line = line.rstrip()
            user_content_lines = []
            just_ended_tool_use = False
            i += 1
            continue

        # --- 处理分隔线 ---
        if RE_SEP_LINE.match(line):
            if in_agent_block:
                if not agent_header_sep_consumed:
                    # Agent角色行后的第一个---：SpecStory固定结构，丢弃
                    agent_header_sep_consumed = True
                elif just_ended_tool_use:
                    # tool-use结束后紧跟的---：SpecStory块分隔线，丢弃
                    just_ended_tool_use = False
                else:
                    # Agent正文内部的---：AI回复的章节分隔线，保留
                    agent_content_lines.append(line)
            elif in_user_block:
                # User块内的---：丢弃
                pass
            else:
                output_lines.append(line)
            i += 1
            continue

        # --- 普通内容行 ---
        just_ended_tool_use = False
        if in_agent_block:
            agent_content_lines.append(line)
        elif in_user_block:
            user_content_lines.append(line)
        else:
            output_lines.append(line)

        i += 1

    # 循环结束后，输出残留块
    if in_agent_block:
        flush_agent()
    elif in_user_block:
        flush_user(user_role_line, user_content_lines)

    return '\n'.join(output_lines)


def _collapse_separators(text: str) -> str:
    """
    将连续的 `---` 分隔线（中间可能有空行）合并为单个 `---` + 一个空行。
    依据：指令文件第89-96行（删除tool-use/thinking后留下连续---和空行）
    """
    # 先把 连续空行 压缩为最多2个空行（保留段落感）
    text = re.sub(r'\n{3,}', '\n\n', text)

    # 把 "---\n\n---" 或 "---\n---" 这类连续分隔线合并
    # 循环替换直到稳定（因为可能有3个以上连续分隔线）
    prev = None
    while prev != text:
        prev = text
        text = re.sub(r'(^---[ \t]*$\n+)+---[ \t]*$', '---', text, flags=re.MULTILINE)

    # 确保 --- 前后各有一个空行
    text = re.sub(r'\n*(^---[ \t]*$)\n*', r'\n\n---\n\n', text, flags=re.MULTILINE)

    # 再次压缩多余空行
    text = re.sub(r'\n{3,}', '\n\n', text)

    return text


# ============================================================
# 命令行入口
# ============================================================

def main():
    if len(sys.argv) < 3:
        print('用法：python specstory_clean.py input.md output.md')
        sys.exit(1)

    input_path = Path(sys.argv[1])
    output_path = Path(sys.argv[2])

    if not input_path.exists():
        print(f'错误：输入文件不存在 {input_path}')
        sys.exit(1)

    text = input_path.read_text(encoding='utf-8')
    result = clean_specstory(text)
    # 仅写入 argv[2]（对话导出等目标路径）；绝不回写 input_path（SPE 源目录）
    output_path.write_text(result, encoding='utf-8')
    print(f'清洗完成：{input_path} → {output_path}')
    print(f'原始行数：{len(text.splitlines())}  清洗后行数：{len(result.splitlines())}')


if __name__ == '__main__':
    main()
